spring:
  datasource:
    url: jdbc:mysql://192.168.0.10:3306/db1?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 192.168.0.10
    port: 6000
    password: redis123456
#    cluster:
#      nodes: 192.168.0.10:6379,192.168.0.10:6380,192.168.0.10:6381,192.168.0.11:6379,192.168.0.11:6380,192.168.0.11:6381,192.168.0.12:6379,192.168.0.12:6380,192.168.0.12:6381
#    sentinel:
#      master: mymaster
#      nodes: 192.168.0.10:26379,192.168.0.11:26379,192.168.0.12:26379



mybatis:
  mapper-locations: classpath*:com/demo/mapper/**/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: classpath:com.demo.entity.*
logging:
  config: classpath:log4j2.xml
server:
  servlet:
    context-path: /spring-boot-demo
  port: 8081
  tomcat:
    max-threads: 1000
