# 使用官方提供的openjdk开发镜像作为基础镜像
FROM openjdk:latest

# 将工作目录切换为/usr/local
WORKDIR /usr/local

# 将当前目录下的所有内容复制到/usr/local下
ADD spring-boot-gradle.jar /usr/local
# RUN mv spring-boot-gradle-1.0.0.jar spring-boot-gradle.jar

# 允许外界访问容器的80端口
EXPOSE 80

# 设置环境变量
#ENV NAME World

# 容器启动时执行的启动的命令
CMD ["java", "-jar", "spring-boot-gradle.jar"]